// <auto-generated />
namespace kus_pluralsight2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OverrideConventionsForGigaAndGenres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverrideConventionsForGigaAndGenres));
        
        string IMigrationMetadata.Id
        {
            get { return "201903241247031_OverrideConventionsForGigaAndGenres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
